# Generated by Django 4.0.1 on 2022-01-16 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='first',
            name='full_name',
            field=models.DateField(),
        ),
    ]
